### ISSUE TITLE
Crash In -[BOZPongRefreshControl setGamePiecePositionsForAnimationStop:]

### ISSUE THREAD

**Issue by iAdam1n** [hbang/Pheromone#20]
Crash: https://ghostbin.com/paste/7xo2v

Syslog: https://ghostbin.com/paste/qq2bq

**Comment by nintyapple** [comment]
pir8
![PIRACY IS BAD PLS NO PIRACY](https://cloud.githubusercontent.com/assets/5097035/8996888/a63cf44e-36e9-11e5-8db4-d3b721dcf308.jpg)

**Comment by kirb** [comment]
Closing as dupe of #18.
