### ISSUE TITLE
Individual sources

### ISSUE THREAD

**Issue by jayreddin** [hbang/Pheromone#7]
the individual sources banner under sources stays staic and stays in the top middle of the screen

**Comment by jayreddin** [comment]
Static

**Comment by jayreddin** [comment]
Only when refreshing sources

**Comment by ReddestDream** [comment]
I noticed the same thing:

https://github.com/hbang/Pheromone/issues/6

**Comment by kirb** [comment]
Do you mean the same as what @ReddestDream reported? If so I'll close this issue as a duplicate of that one.

**Comment by jayreddin** [comment]
Yeah I presume it is the same. Its as sources are loading the individual sources banner stays static on screen and doesn't move move with the rest of the screen

**Comment by jayreddin** [comment]
Found another. As sources are loading if you press edit the ping pong animations stay on screen until you press done. Even after sources stop loading.

**Comment by jayreddin** [comment]
Also the ping pong animation freezes on screen if you keep pressing the "Refresh/X" in the top left corner

**Comment by ReddestDream** [comment]
I've also reported freezing issues with the pong animation although I did not try editing sources.

https://github.com/hbang/Pheromone/issues/6
